name: release-build

on:
  workflow_run:
    workflows:
      - "CI"
    branches: [ main ]
    types:
      - completed

permissions:
  contents: write
  packages: write
  pull-requests: read
  issues: write
  id-token: write
  attestations: write

jobs:
  semantic-release:
    if: "${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.commits[0].message, 'chore(release):') }}"
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Create empty semantic_release_version.txt file
        run: touch semantic_release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=$(cat semantic_release_version.txt)" >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
        with:
          platforms: linux/amd64,linux/arm64

      - name: Docker Login in GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        if: ${{ env.VERSION != '' }}
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        if: ${{ env.VERSION != '' }}
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.VERSION }}

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        id: build-push
        if: ${{ env.VERSION != '' }}
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up cosign
        if: ${{ env.VERSION != '' }}
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6

      - name: Sign Container Image
        if: ${{ env.VERSION != '' }}
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository }}:${{ env.VERSION }} -y
        shell: bash
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Check images
        if: ${{ env.VERSION != '' }}
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker pull ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          cosign verify --key env://COSIGN_PUBLIC_KEY ghcr.io/${{ github.repository }}:${{ env.VERSION }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        if: ${{ env.VERSION != '' }}
        with:
          image: ghcr.io/${{ github.repository }}:${{ env.VERSION }}

      - uses: anchore/sbom-action/publish-sbom@e22c389904149dbc22b58101806040fa8d37a610
        if: ${{ env.VERSION != '' }}
        with:
          sbom-artifact-match: ".*\\.spdx$"

    outputs:
      version: ${{ env.VERSION }}
